# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvindex', '0004_auto_20170225_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie1', models.CharField(blank=True, max_length=100, null=True)),
                ('movie2', models.CharField(blank=True, max_length=100, null=True)),
                ('movie3', models.CharField(blank=True, max_length=100, null=True)),
                ('movie4', models.CharField(blank=True, max_length=100, null=True)),
                ('movie5', models.CharField(blank=True, max_length=100, null=True)),
                ('movie6', models.CharField(blank=True, max_length=100, null=True)),
                ('movie7', models.CharField(blank=True, max_length=100, null=True)),
                ('movie8', models.CharField(blank=True, max_length=100, null=True)),
                ('movie9', models.CharField(blank=True, max_length=100, null=True)),
                ('movie10', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(blank=True, max_length=500, null=True)),
                ('question2', models.CharField(blank=True, max_length=500, null=True)),
                ('question3', models.CharField(blank=True, max_length=500, null=True)),
                ('question4', models.CharField(blank=True, max_length=500, null=True)),
                ('question5', models.CharField(blank=True, max_length=500, null=True)),
                ('question6', models.CharField(blank=True, max_length=500, null=True)),
                ('question7', models.CharField(blank=True, max_length=500, null=True)),
                ('question8', models.CharField(blank=True, max_length=500, null=True)),
                ('question9', models.CharField(blank=True, max_length=500, null=True)),
                ('question10', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
