# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvindex', '0005_movie_titles_newuser_questionaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='question1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
